version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_foodgram:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: dmsvalik/foodgram_backend
    restart: on-failure
    volumes:
      - data_foodgram:/app/data/
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    image: dmsvalik/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
     - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - frontend
      

volumes:
  db_foodgram:
  data_foodgram:
  static_foodgram:
  media_foodgram: