version: '3.3'

services:

  db:
    image: postgres:13
    container_name: foodgram_db
    restart: always
    volumes:
      - db_foodgram:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: dmsvalik/foodgram_backend/.
    container_name: foodgram_backend
    restart: on-failure
    volumes:
      - data_foodgram:/app/data/
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - db
    links:
      - db:db
    env_file: .env

  frontend:
    image: dmsvalik/foodgram_frontend/.
    container_name: foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    container_name: foodgram_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_foodgram:
  data_foodgram:
  static_foodgram:
  media_foodgram: