# Generated by Django 3.2.19 on 2023-08-07 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelist',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления: 1 минута!'), django.core.validators.MaxValueValidator(1000, message='Максимальное время приготовления: 1000 минут!')], verbose_name='Время приготовления в минутах'),
        ),
    ]
